name: Compile dylib

on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
    - name: Compile Tweak
      run: |
        export THEOS=$HOME/theos
        make
